"""empty message

Revision ID: 5b70f8cbf7b6
Revises: 5315ef3005c4
Create Date: 2020-06-17 01:13:33.636441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b70f8cbf7b6'
down_revision = '5315ef3005c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('not_done', sa.Boolean(), nullable=True))
    op.drop_column('activity', 'complete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('complete', sa.BOOLEAN(), nullable=True))
    op.drop_column('activity', 'not_done')
    # ### end Alembic commands ###
